### PR TITLE
Easy to use Jupyter Notebook for Youtube video inference

### PR DESCRIPTION
**Pull request by ArthurFDLR**
This PR adds a Jupyter Notebook including Colab forms to ease Whisper inference on Youtube videos.
This is mainly meant for non-technical folks, but I find the parameter selection GUI pretty useful for high-level experimentation.

I'll create a new discussion on the [show and tell](https://github.com/openai/whisper/discussions/categories/show-and-tell) about this Notebook if you prefer not to add it to the repo.

### CODE REVIEW

**Review by ProjectEGU — COMMENTED** [review]
Is it necessary to include your output in the .ipynb file?

**Comment by ArthurFDLR** [comment]
Thanks for your input; I've cleared the cells.

**Comment by jongwook** [comment]
Hi! Thanks a lot for the contribution; I would very much appreciate if you could post this at Show & Tell.

**Comment by ArthurFDLR** [comment]
Just posted in Show & Tell (#239)

**Comment by jongwook** [comment]
Thanks a lot!

**Pull request closed without merging**
