### PR TITLE
Integrate Pytorch's TorchDynamo as a passed in callable [1.375x faster on A100] [Needs more benchmarking]

### PR DESCRIPTION
**Pull request by voznesenskym**

### CODE REVIEW

**Comment by oscardssmith** [comment]
Do you want benchmarks on an rtx 2060?

**Comment by Sharrnah** [comment]
Can someone provide any info in how to actually use this change?
My guess is that you have to set TorchDynamo to Whisper somehow. but nor sure how.

TorchDynamo documentation writes about decorating a method with `@dynamo.optimize("inductor")` but that's not used in this change.

I could provide benchmark on a RTX 3090 or GTX 1080.

**Comment by voznesenskym** [comment]
> Can someone provide any info in how to actually use this change?
> 
> My guess is that you have to set TorchDynamo to Whisper somehow. but nor sure how.
> 
> 
> 
> TorchDynamo documentation writes about decorating a method with `@dynamo.optimize("inductor")` but that's not used in this change.
> 
> 
> 
> I could provide benchmark on a RTX 3090 or GTX 1080.

Hey! I can take a look today. We ported dynamo into pytorch and it underwent some renaming. My apologies for falling behind on this.

**Comment by jongwook** [comment]
Thanks, I'll close this for now, since it doesn't quite yet work "out of the box" and relying on nightly versions makes things difficult for me to maintain. I'm hoping to get an easier integration with the stable PyTorch 2 interface once it's out.

**Pull request closed without merging**
