### PR TITLE
Added --output option

### PR DESCRIPTION
**Pull request by Aaryan369**
Instead of generating all the 3(txt, vtt and srt) type of files, --output options helps us choose if we want to generate no files, some files or all files. 
(I added this feature because when I was running a lot of files, unwanted files are getting generated which are filling up the system.)

Also fixed the logical error in tqdm pbar, which was printing the pbar even when the verbose was set to False.
(Edit: I just realized that this was intended, but shouldn't verbose=False mean no output must be shown?)

### CODE REVIEW

**Comment by bottledmind** [comment]
@Aaryan369 check [this one](https://github.com/openai/whisper/pull/140) for details on verbosity

**Comment by Aaryan369** [comment]
> @Aaryan369 check [this one](https://github.com/openai/whisper/pull/140) for details on verbosity

@bottledmind Thanks for pointing it out, reverted the changes regarding pbar and verbosity in my code.

**Comment by mliradelc** [comment]
Thanks for the PR!, I hope whisper team merge it.

**Comment by jongwook** [comment]
Thanks for the PR! I've renamed the option to `--output_format` and moved some code around.

**Comment by Aaryan369** [comment]
Thanks for committing my PR @jongwook and for making the necessary changes! 
I appreciate your attention to detail and your efforts to improve the project.

**Pull request merged**
